export type RegistrationStatus='SCANNED'|'SANTRI_SELECTED'|'PIN_SET'|'COMPLETED'|'EXPIRED'|'CANCELLED';
export interface RegistrationSession {id:string;tenantId:string;terminalId:string;cardUid:string;santriId:string|null;status:RegistrationStatus;expiresAt:Date;}
export interface RegisteredCard {id:string;tenantId:string;santriId:string;cardUid:string;status:'ACTIVE'|'FROZEN'|'REPLACED'|'REVOKED'|'INACTIVE';consecutiveNegativeDebits:number;}
export interface CardRegistrationRepository { runSerializable<T>(tenantId:string,work:()=>Promise<T>):Promise<T>; terminalType(tenantId:string,terminalId:string):Promise<'MERCHANT'|'ADMIN'|undefined>; findActiveCardByUid(tenantId:string,cardUid:string):Promise<RegisteredCard|undefined>;findOpenSessionByUid(tenantId:string,cardUid:string,now:Date):Promise<RegistrationSession|undefined>; createSession(input:Omit<RegistrationSession,'id'|'status'|'expiresAt'> & {expiresAt:Date}):Promise<RegistrationSession>; lockSession(tenantId:string,id:string):Promise<RegistrationSession|undefined>; selectSantri(tenantId:string,sessionId:string,santriId:string):Promise<void>; expireSession(tenantId:string,id:string):Promise<void>; findReplaceableCard(tenantId:string,santriId:string):Promise<RegisteredCard|undefined>; markReplaced(tenantId:string,cardId:string):Promise<void>; createCard(input:{tenantId:string;santriId:string;cardUid:string;pinHash:string;replacedFromCardId:string|null;consecutiveNegativeDebits:number}):Promise<RegisteredCard>; completeSession(tenantId:string,id:string):Promise<void>; hashPin(value:string):Promise<string>; appendAudit(input:{tenantId:string;action:'CARD_REGISTERED'|'CARD_REPLACED';resourceId:string;metadata:Record<string,unknown>}):Promise<void>; }
export class CardRegistrationError extends Error {constructor(public readonly code:'TERMINAL_TYPE_NOT_ALLOWED'|'CARD_ALREADY_REGISTERED'|'REGISTRATION_SESSION_EXPIRED'|'CARD_NOT_ACTIVE',message:string){super(message);}}
export class CardRegistrationService {constructor(private readonly repository:CardRegistrationRepository){}
 async handleCardScan(tenantId:string,terminalId:string,cardUid:string,now=new Date()){if(await this.repository.terminalType(tenantId,terminalId)!=='ADMIN')throw new CardRegistrationError('TERMINAL_TYPE_NOT_ALLOWED','Terminal ini bukan terminal Admin Pesantren.');if(await this.repository.findActiveCardByUid(tenantId,cardUid))throw new CardRegistrationError('CARD_ALREADY_REGISTERED','Kartu sudah terdaftar.');if(await this.repository.findOpenSessionByUid(tenantId,cardUid,now))throw new CardRegistrationError('CARD_ALREADY_REGISTERED','Kartu sedang dalam proses pendaftaran.');return this.repository.createSession({tenantId,terminalId,cardUid,santriId:null,expiresAt:new Date(now.getTime()+5*60_000)});}
 async selectSantriForRegistration(tenantId:string,sessionId:string,santriId:string,now=new Date()){return this.repository.runSerializable(tenantId,async()=>{const session=await this.requireSelectedSession(tenantId,sessionId,now,'SCANNED');await this.repository.selectSantri(tenantId,session.id,santriId);});}
 async finalizeCardRegistration(tenantId:string,sessionId:string,pinHashLocal:string,terminalId:string,now=new Date()){return this.repository.runSerializable(tenantId,async()=>{const session=await this.requireSelectedSession(tenantId,sessionId,now,'SANTRI_SELECTED');if(session.terminalId!==terminalId)throw new CardRegistrationError('TERMINAL_TYPE_NOT_ALLOWED','Terminal tidak sesuai dengan sesi pendaftaran.');const old=await this.repository.findReplaceableCard(tenantId,session.santriId!);if(old)await this.repository.markReplaced(tenantId,old.id);const card=await this.repository.createCard({tenantId:session.tenantId,santriId:session.santriId!,cardUid:session.cardUid,pinHash:await this.repository.hashPin(pinHashLocal),replacedFromCardId:old?.id??null,consecutiveNegativeDebits:old?.consecutiveNegativeDebits??0});await this.repository.completeSession(tenantId,session.id);await this.repository.appendAudit({tenantId:session.tenantId,action:old?'CARD_REPLACED':'CARD_REGISTERED',resourceId:card.id,metadata:{santriId:session.santriId,carriedOverCounter:card.consecutiveNegativeDebits}});return card;});}
 private async requireSelectedSession(tenantId:string,id:string,now:Date,expected:RegistrationStatus){const session=await this.repository.lockSession(tenantId,id);if(!session||session.status!==expected||session.expiresAt<now){if(session&&session.status!== 'COMPLETED')await this.repository.expireSession(tenantId,session.id);throw new CardRegistrationError('REGISTRATION_SESSION_EXPIRED','Sesi pendaftaran telah kedaluwarsa atau tidak valid.');}return session;}
}
