-- Phase 2 ledger core. All amounts remain NUMERIC in PostgreSQL; application boundaries accept
-- integer Rupiah only until a currency sub-unit policy is explicitly introduced.
CREATE TABLE cards (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), santri_id UUID NOT NULL REFERENCES santri(id), card_uid VARCHAR(40) NOT NULL, pin_hash TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', consecutive_negative_debits INT NOT NULL DEFAULT 0, issued_at TIMESTAMPTZ NOT NULL DEFAULT now(), replaced_from_card_id UUID REFERENCES cards(id), UNIQUE(tenant_id,card_uid));
CREATE TABLE merchants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), name VARCHAR(150) NOT NULL, category VARCHAR(50), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE terminals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), merchant_id UUID REFERENCES merchants(id), terminal_type VARCHAR(20) NOT NULL DEFAULT 'MERCHANT', device_id VARCHAR(80) UNIQUE NOT NULL, device_token_hash TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', CHECK ((terminal_type='MERCHANT' AND merchant_id IS NOT NULL) OR (terminal_type='ADMIN' AND merchant_id IS NULL)));
CREATE TABLE card_registration_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), terminal_id UUID NOT NULL REFERENCES terminals(id), card_uid VARCHAR(40) NOT NULL, santri_id UUID REFERENCES santri(id), status VARCHAR(20) NOT NULL DEFAULT 'SCANNED', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), entity_type VARCHAR(30) NOT NULL, entity_id UUID NOT NULL, currency VARCHAR(3) NOT NULL DEFAULT 'IDR', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(tenant_id,entity_type,entity_id));
CREATE TABLE ledger_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), journal_id UUID NOT NULL, account_id UUID NOT NULL REFERENCES accounts(id), entry_type VARCHAR(6) NOT NULL CHECK(entry_type IN ('DEBIT','KREDIT')), amount NUMERIC(15,2) NOT NULL CHECK(amount>0), balance_snapshot NUMERIC(15,2), description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_ledger_account_date ON ledger_entries(account_id,created_at DESC); CREATE INDEX idx_ledger_journal ON ledger_entries(journal_id);
CREATE TABLE transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), journal_id UUID NOT NULL UNIQUE, transaction_type VARCHAR(30) NOT NULL, card_id UUID REFERENCES cards(id), santri_id UUID REFERENCES santri(id), merchant_id UUID REFERENCES merchants(id), terminal_id UUID REFERENCES terminals(id), operator_id UUID REFERENCES staff_users(id), withdrawal_reason VARCHAR(50), amount NUMERIC(15,2) NOT NULL CHECK(amount>0), status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS', idempotency_key VARCHAR(80) UNIQUE NOT NULL, voided_by UUID REFERENCES staff_users(id), voided_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_transactions_santri_date ON transactions(santri_id,created_at DESC); CREATE INDEX idx_transactions_merchant_type_date ON transactions(merchant_id,transaction_type,created_at DESC);
CREATE TABLE merchant_settlement_invoices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), merchant_id UUID NOT NULL REFERENCES merchants(id), period_start DATE NOT NULL, period_end DATE NOT NULL, opening_balance NUMERIC(15,2) NOT NULL, total_sales NUMERIC(15,2) NOT NULL DEFAULT 0, total_withdrawals_paid NUMERIC(15,2) NOT NULL DEFAULT 0, total_topup_collected NUMERIC(15,2) NOT NULL DEFAULT 0, closing_balance NUMERIC(15,2) NOT NULL, settlement_action VARCHAR(20) NOT NULL DEFAULT 'PENDING', status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', UNIQUE(tenant_id,merchant_id,period_start,period_end));
-- Immutable tables: corrections require a new reversal entry/audit record, never data mutation.
CREATE FUNCTION reject_immutable_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable table: % cannot be updated or deleted', TG_TABLE_NAME USING ERRCODE='55000'; END; $$;
CREATE TRIGGER ledger_entries_immutable BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();
CREATE TRIGGER audit_logs_immutable BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();
-- RLS is forced even for the owner. The application role must not have BYPASSRLS.
ALTER TABLE cards ENABLE ROW LEVEL SECURITY; ALTER TABLE cards FORCE ROW LEVEL SECURITY;
ALTER TABLE merchants ENABLE ROW LEVEL SECURITY; ALTER TABLE merchants FORCE ROW LEVEL SECURITY;
ALTER TABLE terminals ENABLE ROW LEVEL SECURITY; ALTER TABLE terminals FORCE ROW LEVEL SECURITY;
ALTER TABLE card_registration_sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE card_registration_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY; ALTER TABLE accounts FORCE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY; ALTER TABLE ledger_entries FORCE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY; ALTER TABLE transactions FORCE ROW LEVEL SECURITY;
ALTER TABLE merchant_settlement_invoices ENABLE ROW LEVEL SECURITY; ALTER TABLE merchant_settlement_invoices FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_cards ON cards USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_merchants ON merchants USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_terminals ON terminals USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_card_registration_sessions ON card_registration_sessions USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_accounts ON accounts USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_ledger_entries ON ledger_entries USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_transactions ON transactions USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_merchant_settlement_invoices ON merchant_settlement_invoices USING(tenant_id=current_setting('app.current_tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.current_tenant_id',true)::uuid);
