import argon2 from 'argon2'; import jwt from 'jsonwebtoken'; import crypto from 'node:crypto';
import { env } from '../../config/env.js'; import { prisma } from '../../db/client.js'; import { AppError } from '../../shared/errors.js'; import type { JwtClaims } from '@pondokpay/shared-types'; import { staffClaims, waliClaims } from './auth-claims.js'; import { issueWaliTenantAccessToken } from './auth-token.service.js';
const hashToken=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
export class AuthService {
 async login(email:string,password:string) { const staff=await prisma.staffUser.findUnique({where:{email},include:{tenant:true}}); const wali=staff?null:await prisma.waliSantri.findUnique({where:{email}}); const user=staff??wali; if(!user||user.status!=='ACTIVE'||!await argon2.verify(user.passwordHash,password)) throw new AppError('UNAUTHORIZED','Email atau kata sandi tidak valid.',401);
 const claims:JwtClaims=staff?staffClaims({id:staff.id,role:staff.role,tenantId:staff.tenantId,merchantScope:staff.merchantScope}):waliClaims(wali!.id);
 if(staff?.tenant?.status==='SUSPENDED'&&staff.role!=='ADMIN_PESANTREN') throw new AppError('TENANT_SUSPENDED','Sistem sedang tidak tersedia.',403);
 const accessToken=jwt.sign(claims,env.JWT_ACCESS_SECRET,{expiresIn:env.JWT_ACCESS_EXPIRY as jwt.SignOptions['expiresIn']}); const refreshToken=crypto.randomBytes(48).toString('base64url');
 await prisma.refreshToken.create({data:{tokenHash:hashToken(refreshToken),staffUserId:staff?.id,waliSantriId:wali?.id,expiresAt:new Date(Date.now()+7*864e5)}}); if(staff) await prisma.staffUser.update({where:{id:staff.id},data:{lastLoginAt:new Date()}});
 return {accessToken,refreshToken,user:{id:claims.sub,role:claims.role,tenant_id:claims.tenant_id,merchant_scope:claims.merchant_scope}};
 }
 async refresh(raw:string) { const token=await prisma.refreshToken.findUnique({where:{tokenHash:hashToken(raw)},include:{staffUser:{include:{tenant:true}},waliSantri:true}}); if(!token||token.revokedAt||token.expiresAt<new Date()) throw new AppError('UNAUTHORIZED','Sesi tidak valid atau telah berakhir.',401); await prisma.refreshToken.update({where:{id:token.id},data:{revokedAt:new Date()}}); const source=token.staffUser??token.waliSantri!; return this.loginWithIdentity(source,token.staffUser?.role,token.staffUser?.tenantId,token.staffUser?.merchantScope??[]); }
 private async loginWithIdentity(user:{id:string},role:any,tenantId:string|null|undefined,merchantScope:string[]) { const claims:JwtClaims={sub:user.id,role:role??'WALI_SANTRI',tenant_id:tenantId??null,merchant_scope:merchantScope}; const accessToken=jwt.sign(claims,env.JWT_ACCESS_SECRET,{expiresIn:env.JWT_ACCESS_EXPIRY as jwt.SignOptions['expiresIn']}); const refreshToken=crypto.randomBytes(48).toString('base64url'); await prisma.refreshToken.create({data:{tokenHash:hashToken(refreshToken),staffUserId:role?user.id:null,waliSantriId:role?null:user.id,expiresAt:new Date(Date.now()+7*864e5)}}); return {accessToken,refreshToken,user:{id:claims.sub,role:claims.role,tenant_id:claims.tenant_id,merchant_scope:claims.merchant_scope}}; }
 issueWaliTenantAccessToken(waliId:string,tenantId:string){return issueWaliTenantAccessToken(waliId,tenantId);}
 async logout(raw:string){ if(raw) await prisma.refreshToken.updateMany({where:{tokenHash:hashToken(raw),revokedAt:null},data:{revokedAt:new Date()}}); }
}
